version: '3.8'

services:
  notes-client:
    build: .
    container_name: notes-client
    image: notes-client
    ports:
      - "3000:80"
    networks:
      - main_network

networks:
  main_network:
    external: true
